import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { getAdminByEmail } from '../data/mockData';

export default function TechLogin({ setUser }) {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const handleLogin = (e) => {
    e.preventDefault();
    setError('');

    const userObj = getAdminByEmail(email);

    if (userObj && userObj.password === password) {
      if (userObj.role === 'technician') {
        localStorage.setItem('adminUser', JSON.stringify(userObj));
        setUser(userObj);
        navigate('/technician');
      } else {
        setError('This portal is only for technicians. Admins please use the Admin Portal.');
      }
    } else {
      setError('Invalid email or password');
    }
  };

  return (
    <div style={{
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: '#FFFFFF',
      padding: '20px',
      color: '#1F2937',
      fontFamily: 'Inter, sans-serif'
    }}>
      <div style={{
        background: '#FFFFFF',
        border: '1px solid #E5E7EB',
        borderRadius: '24px',
        padding: '40px',
        width: '100%',
        maxHeight: '90vh',
        overflowY: 'auto',
        maxWidth: '460px',
        boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.05), 0 10px 10px -5px rgba(0, 0, 0, 0.02)'
      }}>
        <div style={{ textAlign: 'center', marginBottom: '32px' }}>
          <div style={{
            background: 'linear-gradient(135deg, #3B82F6 0%, #2563EB 100%)',
            color: 'white',
            width: '64px',
            height: '64px',
            borderRadius: '16px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: '28px',
            fontWeight: '800',
            margin: '0 auto 16px auto',
            boxShadow: '0 10px 25px -5px rgba(59, 130, 246, 0.4)'
          }}>SF</div>
          <h1 style={{ fontSize: '26px', fontWeight: '800', color: '#1F2937', margin: '0 0 8px 0' }}>Technician Login</h1>
          <p style={{ color: '#6B7280', fontSize: '14px', margin: 0 }}>Sign in to access your hall assignments</p>
        </div>

        <div style={{
          background: '#EFF6FF',
          border: '1px solid #DBEAFE',
          borderRadius: '12px',
          padding: '16px',
          marginBottom: '24px',
          fontSize: '13px',
          color: '#1E40AF',
          lineHeight: '1.5'
        }}>
          💡 <strong>Notice:</strong> Your credentials (email and password) are generated by your administrator when you are added as staff. There are no demo logins — contact your administrator if you don't have credentials yet.
        </div>

        {error && (
          <div style={{
            background: '#FEE2E2',
            border: '1px solid #FCA5A5',
            borderRadius: '8px',
            padding: '12px 16px',
            color: '#DC2626',
            fontSize: '14px',
            marginBottom: '20px',
            textAlign: 'center'
          }}>
            ⚠️ {error}
          </div>
        )}

        <form onSubmit={handleLogin}>
          <div style={{ marginBottom: '20px' }}>
            <label style={{ display: 'block', marginBottom: '8px', fontSize: '13px', fontWeight: '500', color: '#4B5563' }}>Email Address</label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="Enter your email"
              required
              style={{
                width: '100%',
                padding: '12px 16px',
                background: '#FFFFFF',
                border: '1px solid #D1D5DB',
                borderRadius: '10px',
                color: '#1F2937',
                fontSize: '14px',
                outline: 'none',
                boxSizing: 'border-box'
              }}
            />
          </div>

          <div style={{ marginBottom: '28px' }}>
            <label style={{ display: 'block', marginBottom: '8px', fontSize: '13px', fontWeight: '500', color: '#4B5563' }}>Password</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Enter your temporary password"
              required
              style={{
                width: '100%',
                padding: '12px 16px',
                background: '#FFFFFF',
                border: '1px solid #D1D5DB',
                borderRadius: '10px',
                color: '#1F2937',
                fontSize: '14px',
                outline: 'none',
                boxSizing: 'border-box'
              }}
            />
          </div>

          <button type="submit" style={{
            width: '100%',
            padding: '14px',
            background: 'linear-gradient(135deg, #3B82F6 0%, #2563EB 100%)',
            border: 'none',
            borderRadius: '10px',
            color: '#FFFFFF',
            fontSize: '15px',
            fontWeight: '600',
            cursor: 'pointer',
            boxShadow: '0 4px 12px rgba(37, 99, 235, 0.2)',
            transition: 'all 0.2s'
          }}>
            Sign In
          </button>
        </form>

        <div style={{ marginTop: '24px', textAlign: 'center' }}>
          <Link to="/login" style={{ color: '#3B82F6', fontWeight: '500', textDecoration: 'none', fontSize: '13px' }}>
            🏛️ Administrator? Go to Admin Portal →
          </Link>
        </div>
      </div>
    </div>
  );
}
